/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_stock.menu;

import gestion_stock.Connect;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdouramane
 */
public class FormulaireFourniss extends javax.swing.JFrame {
 Connect con = new Connect();
    Statement st;
    ResultSet rs;
    DefaultTableModel model= new DefaultTableModel();
    /**
     * Creates new form FormulaireFourniss
     */
    public FormulaireFourniss() {
        initComponents();
        
model.addColumn("Numero");
model.addColumn("Nom du Fournisseur");
model.addColumn("Adresse du Fournisseur");
model.addColumn("Telephone");

try{
st=Connect.getConnection().createStatement();
rs=st.executeQuery("SELECT *FROM FOURNISSEUR");
while(rs.next())
{
model.addRow(new Object[]{rs.getString("idF"), rs.getString("NomF"), rs.getString("AdesF"), rs.getString("TelepF")});}
}
catch(Exception e){
System.err.println(e);}
table.setModel(model);
    

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TextFieldi = new javax.swing.JTextField();
        TextFieldf = new javax.swing.JTextField();
        TxtFieldF = new javax.swing.JTextField();
        TextFieldA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ButtonAjF = new javax.swing.JButton();
        ButtonAjCl1 = new javax.swing.JButton();
        ButtonAjCl2 = new javax.swing.JButton();
        ButtonActua = new javax.swing.JButton();
        buttonRC = new javax.swing.JButton();
        TextFieldRC = new javax.swing.JTextField();
        RetCheckBox2 = new javax.swing.JCheckBox();
        LiCheckBox3 = new javax.swing.JCheckBox();
        ButtonActua1 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel33.setBackground(new java.awt.Color(0, 0, 102));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Numero");

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nom du Fournisseur");

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Adresse du Fournisseur");

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Téléphone du Fournisseur");

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 51), null, new java.awt.Color(51, 0, 51)));
        table.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Nom du Fournisseur", "Adresse du Fournisseur", "Téléphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        ButtonAjF.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ajouter.png"))); // NOI18N
        ButtonAjF.setText("Ajouter");
        ButtonAjF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjFActionPerformed(evt);
            }
        });

        ButtonAjCl1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/modifier.png"))); // NOI18N
        ButtonAjCl1.setText("Modifier");
        ButtonAjCl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjCl1ActionPerformed(evt);
            }
        });

        ButtonAjCl2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer.png"))); // NOI18N
        ButtonAjCl2.setText("Supprimer");
        ButtonAjCl2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjCl2ActionPerformed(evt);
            }
        });

        ButtonActua.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonActua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/actualiser.png"))); // NOI18N
        ButtonActua.setText("Actualiser");
        ButtonActua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonActua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActuaActionPerformed(evt);
            }
        });

        buttonRC.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        buttonRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/rechercher.png"))); // NOI18N
        buttonRC.setText("Recherche");
        buttonRC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 0), null, new java.awt.Color(102, 102, 0)));
        buttonRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRCActionPerformed(evt);
            }
        });

        RetCheckBox2.setBackground(new java.awt.Color(0, 0, 102));
        RetCheckBox2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        RetCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        RetCheckBox2.setText("Retour");
        RetCheckBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, new java.awt.Color(51, 51, 0)));
        RetCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetCheckBox2ActionPerformed(evt);
            }
        });

        LiCheckBox3.setBackground(new java.awt.Color(0, 0, 102));
        LiCheckBox3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LiCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        LiCheckBox3.setText("Livraison");
        LiCheckBox3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, new java.awt.Color(51, 51, 0)));
        LiCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiCheckBox3ActionPerformed(evt);
            }
        });

        ButtonActua1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonActua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/imprimer.png"))); // NOI18N
        ButtonActua1.setText("Imprimer");
        ButtonActua1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonActua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(319, 319, 319)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldA)
                            .addComponent(TxtFieldF)))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(buttonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(364, 364, 364)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldRC)
                            .addComponent(TextFieldf)
                            .addComponent(TextFieldi))))
                .addGap(85, 85, 85))
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ButtonAjF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(ButtonAjCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ButtonAjCl2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonActua, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonActua1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(LiCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RetCheckBox2)
                                .addGap(212, 212, 212)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldRC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TextFieldf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(TextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TxtFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonAjF)
                        .addComponent(ButtonAjCl1)
                        .addComponent(ButtonAjCl2)
                        .addComponent(ButtonActua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonActua1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(LiCheckBox3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetCheckBox2)
                        .addGap(19, 19, 19))))
        );

        jPanel34.setBackground(new java.awt.Color(255, 255, 0));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel17.setText("Fournisseurs");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try{
            int i =table.getSelectedRow(); deplace(i);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void ButtonAjFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjFActionPerformed

        String id=TextFieldi.getText();
        String nom=TextFieldf.getText();
        String ad=TextFieldA.getText();
        String tel=TxtFieldF.getText();
        
        
        

        String query = "INSERT INTO `fournisseur`(`idF`, `NomF`, `AdesF`, `TelepF`) VALUES ('"+id+"','"+nom+"','"+ad+"','"+tel+"')";

        try{
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"FOURNISSEUR ajouté avec succès");

            TextFieldi.setText("");
            TextFieldf.setText("");
            TextFieldA.setText("");
            TxtFieldF.setText("");

        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_ButtonAjFActionPerformed

    private void ButtonAjCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjCl1ActionPerformed
        try{
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
            updatebtn();
            st.executeUpdate("UPDATE FOURNISSEUR SET NomF='"+TextFieldf.getText()+"',AdesF='"+TextFieldA.getText()+"',TelepF='"+TxtFieldF.getText()+"' WHERE idF= "+TextFieldi.getText());

        }

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,"erreur de modifier !!!!!!!"+e.getMessage());
            System.err.println(e);}
    }//GEN-LAST:event_ButtonAjCl1ActionPerformed

    private void ButtonAjCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjCl2ActionPerformed
        try {

            if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer un cient,est ce que tu est sure?"
                ,"supprimer FOURNISSEUR",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)

        if(TextFieldi.getText().length() != 0){
            st.executeUpdate("DELETE FROM FOURNISSEUR WHERE idF= "+TextFieldi.getText());
        }//
        else { JOptionPane.showMessageDialog(null,"veuillez remplire le champ du numero !");}
        }

        catch(HeadlessException | SQLException e){

            JOptionPane.showMessageDialog(null,"erreur de supprimer \n"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAjCl2ActionPerformed

    private void ButtonActuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActuaActionPerformed
        try{
            model.setRowCount(0);
            st=Connect.getConnection().createStatement();
            rs=st.executeQuery("SELECT *FROM FOURNISSEUR");

            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("idF"), rs.getString("NomF"), rs.getString("AdesF"), rs.getString("TelepF")});
            }

        }
        catch(Exception e){

            System.err.println(e);}

        table.setModel(model);
    }//GEN-LAST:event_ButtonActuaActionPerformed

    private void buttonRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRCActionPerformed
        try{
            model.setRowCount(0);

            {
                rs = st.executeQuery("SELECT * FROM FOURNISSEUR WHERE idF = '"+TextFieldi.getText()+"'");
            }

            while(rs.next())
            {
                Object [] fournisseur ={rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(fournisseur);
            }

            if(model.getRowCount() == 0 )
            {
                JOptionPane.showMessageDialog(null," Aucun FOURNISSEUR disponible");
            }else
            {
                int i=0;
                deplace(i);

            }

        }

        catch(SQLException | HeadlessException e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,e.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRCActionPerformed

    public void updatebtn()
    {
        String nom=TextFieldf.getText();
        String ad=TextFieldA.getText();
        String tel=TxtFieldF.getText();
        String id = TextFieldi.getText();
   
    
    
    
   

    String query = "UPDATE `fournisseur` SET `NomF`='"+nom+"',`AdesF`='"+ad+"',`TelepF`='"+tel+"' WHERE `idF`='"+id+"'";

try{
  st=Connect.getConnection().createStatement();



JOptionPane.showConfirmDialog(null, "Voulez-vous appliquée la modification ?");
st.executeUpdate(query);
}catch(SQLException e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
    }
    private void RetCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetCheckBox2ActionPerformed

    private void LiCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LiCheckBox3ActionPerformed

    private void ButtonActua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActua1ActionPerformed
        MessageFormat header = new MessageFormat("Bon de Commande");
        MessageFormat footer = new MessageFormat("Page[0,number,integer]");

        try{

        table.print(JTable.PrintMode.NORMAL, header, footer);

}catch(java.awt.print.PrinterException e){
System.err.format("Erreur d'impression", e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActua1ActionPerformed

    private void deplace(int i)
{
try{
TextFieldi.setText(model.getValueAt(i, 0).toString());
TextFieldf.setText(model.getValueAt(i, 1).toString());
TextFieldA.setText(model.getValueAt(i, 2).toString());
TxtFieldF.setText(model.getValueAt(i, 3).toString());
    
    
}catch(Exception e){
System.err.println(e);

JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
}
    
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireFourniss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireFourniss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireFourniss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireFourniss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormulaireFourniss().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActua;
    private javax.swing.JButton ButtonActua1;
    private javax.swing.JButton ButtonAjCl1;
    private javax.swing.JButton ButtonAjCl2;
    private javax.swing.JButton ButtonAjF;
    private javax.swing.JCheckBox LiCheckBox3;
    private javax.swing.JCheckBox RetCheckBox2;
    private javax.swing.JTextField TextFieldA;
    private javax.swing.JTextField TextFieldRC;
    private javax.swing.JTextField TextFieldf;
    private javax.swing.JTextField TextFieldi;
    private javax.swing.JTextField TxtFieldF;
    private javax.swing.JButton buttonRC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
