/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_stock.menu;


import gestion_stock.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdouramane
 */
public class FormulaireArticles extends javax.swing.JFrame {
	Connect cn=new Connect();
	Statement st;
	ResultSet rs;
    DefaultTableModel model= new DefaultTableModel();

    /**
     * Creates new form FormulaireArticles
     */
    public FormulaireArticles() {
        initComponents();
        
        
        model.addColumn("idArt");
        model.addColumn("nomArt");
        model.addColumn("stockMini");
        model.addColumn("stockMax");
        
        try{
        st=Connect.getConnection().createStatement();
        rs=st.executeQuery("SELECT *FROM ARTICLE");
        
        while(rs.next())
        { 
            model.addRow(new Object[]{rs.getString("Numero"), rs.getString("Nom de l'article"), rs.getInt("stockMini"), rs.getInt("stockMax")});
        }
        }
        catch(Exception ex){
System.err.println(ex);}
          tables.setModel(model);
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldNum = new javax.swing.JTextField();
        FieldNomArt = new javax.swing.JTextField();
        FieldStMi = new javax.swing.JTextField();
        FieldStMa = new javax.swing.JTextField();
        btnAj = new javax.swing.JButton();
        btnMo = new javax.swing.JButton();
        btnAct = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        ButtonRch = new javax.swing.JButton();
        TextFieldRch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Liste des  Articles");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom de l'article");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock minimum");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock maximum");

        TextFieldNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumActionPerformed(evt);
            }
        });

        FieldNomArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNomArtActionPerformed(evt);
            }
        });

        FieldStMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldStMiActionPerformed(evt);
            }
        });

        FieldStMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldStMaActionPerformed(evt);
            }
        });

        btnAj.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ajouter.png"))); // NOI18N
        btnAj.setText("Ajouter");
        btnAj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 153), null, new java.awt.Color(0, 51, 153)));
        btnAj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjActionPerformed(evt);
            }
        });

        btnMo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnMo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/modifier.png"))); // NOI18N
        btnMo.setText("Modifier");
        btnMo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 153), null, new java.awt.Color(0, 51, 153)));
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        btnAct.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/actualiser.png"))); // NOI18N
        btnAct.setText("Actualiser");
        btnAct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 153), null, new java.awt.Color(0, 51, 153)));
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        btnSup.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer.png"))); // NOI18N
        btnSup.setText("Supprimer");
        btnSup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 153), null, new java.awt.Color(0, 51, 153)));
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        ButtonRch.setBackground(new java.awt.Color(255, 255, 255));
        ButtonRch.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonRch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/rechercher.png"))); // NOI18N
        ButtonRch.setText("Recherche");
        ButtonRch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        ButtonRch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRchActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));

        tables.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        tables.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Nom de l'article", "Stock Minimum", "Stock Maximum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tables);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldNomArt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FieldStMi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(FieldStMa, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(ButtonRch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldNum, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(TextFieldRch))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAj, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnSup)
                .addGap(27, 27, 27)
                .addComponent(btnAct, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldRch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FieldNomArt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldStMi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(FieldStMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAj)
                    .addComponent(btnMo)
                    .addComponent(btnSup)
                    .addComponent(btnAct))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjActionPerformed

 String idA = TextFieldNum.getText();
 String Nom = FieldNomArt.getText();
 String StMi = FieldStMi.getText();
 String StMa = FieldStMa.getText();
 
 String query = "INSERT INTO `article`(`idArt`, `NomArt`, `StockMini`, `StockMax`) VALUES ('"+idA+"','"+Nom+"','"+StMi+"','"+StMa+"')"; 
 try {
  
  if(JOptionPane.showConfirmDialog(this,"voulez-vous ajoutez un article?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
  {
  st.executeUpdate(query);
 JOptionPane.showMessageDialog(this,"insertion éffectuée!");

  }
TextFieldNum.setText("");
FieldNomArt.setText("");
FieldStMi.setText("");
FieldStMa.setText("");

 }catch(SQLException ex){
 JOptionPane.showMessageDialog(this,"impossible d'insérer!",null,JOptionPane.ERROR_MESSAGE);

 }
 
    }//GEN-LAST:event_btnAjActionPerformed

    private void FieldStMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldStMiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldStMiActionPerformed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
String idA = TextFieldNum.getText();
 String Nom = FieldNomArt.getText();
 String StMi = FieldStMi.getText();
 String StMa = FieldStMa.getText();
 
        try {
if(JOptionPane.showConfirmDialog(this,"voulez-vous modifier un l'article?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
 String query ="UPDATE `article` SET `NomArt`='"+Nom+"',`StockMini`='"+StMi+"',`StockMax`='"+StMa+"' WHERE `idArt`='"+idA+"'";
st.executeUpdate(query);
}

}catch(SQLException ex){

JOptionPane.showMessageDialog(this,"impossible de modifier!",null,JOptionPane.ERROR_MESSAGE);
        System.err.println(ex);
} 
        
    }//GEN-LAST:event_btnMoActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        String idA = TextFieldNum.getText();
        String query = "DELETE FROM `article` WHERE idArt='"+idA+"'";
        
        try{
        st=Connect.getConnection().prepareStatement(query);
        if(JOptionPane.showConfirmDialog(this,"voulez-vous supprimer un produit?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
        {
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(this,"Suppression éffectuée avec succès!");

        }
        }catch(SQLException ex)
        {
      JOptionPane.showMessageDialog(this,"Suppression impossible l'article!");
JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }//GEN-LAST:event_btnSupActionPerformed

    private void ButtonRchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRchActionPerformed

try{
model.setRowCount(0);

       {
       rs = st.executeQuery("SELECT * FROM `article` WHERE idArt = '"+TextFieldRch.getText()+"'");
       }
       
       while(rs.next())
       {
              Object [] article ={rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4)};
              model.addRow(article);
       }
       
       if(model.getRowCount() == 0 )
       {
           JOptionPane.showMessageDialog(null," Aucun article disponible");
       }else
       {
           int i=0;
           move(i);
       
       }

}catch(SQLException ex){

JOptionPane.showMessageDialog(this,"codeproduit introuvable!",null,JOptionPane.ERROR_MESSAGE);

}
// TODO add your handling code here:
    }//GEN-LAST:event_ButtonRchActionPerformed

    private void FieldNomArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNomArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNomArtActionPerformed

    private void FieldStMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldStMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldStMaActionPerformed

    private void TextFieldNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumActionPerformed

    private void tablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseClicked
        try{
int i =tables.getSelectedRow(); move(i);

}catch(Exception e){
JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
}        // TODO a
    }//GEN-LAST:event_tablesMouseClicked

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
try{
    model.setRowCount(0);
st=Connect.getConnection().createStatement();
rs=st.executeQuery("SELECT *FROM ARTICLE");

while(rs.next())
{
model.addRow(new Object[]{rs.getInt("idArt"), rs.getString("NomArt"), rs.getInt("stockMini"), rs.getInt("stockMax")});
}

}
catch(Exception e){

System.err.println(e);}  

tables.setModel(model);        // TODO add your handling code here:
    }//GEN-LAST:event_btnActActionPerformed

    
    private void move(int i)
{
try{
TextFieldNum.setText(model.getValueAt(i, 0).toString());
FieldNomArt.setText(model.getValueAt(i, 1).toString());
FieldStMi.setText(model.getValueAt(i, 2).toString());
FieldStMa.setText(model.getValueAt(i, 3).toString());
    
    
}catch(Exception e){
System.err.println(e);

JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
}
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormulaireArticles().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRch;
    private javax.swing.JTextField FieldNomArt;
    private javax.swing.JTextField FieldStMa;
    private javax.swing.JTextField FieldStMi;
    private javax.swing.JTextField TextFieldNum;
    private javax.swing.JTextField TextFieldRch;
    private javax.swing.JButton btnAct;
    private javax.swing.JButton btnAj;
    private javax.swing.JButton btnMo;
    private javax.swing.JButton btnSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tables;
    // End of variables declaration//GEN-END:variables
}
