/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_stock.menu;

import gestion_stock.Connect;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdouramane
 */
public class FormulaireClient extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireClient
     */
    Connect con = new Connect();
    Statement st;
    ResultSet rs;
    DefaultTableModel model= new DefaultTableModel();
    
    public FormulaireClient() {
        initComponents();
        
model.addColumn("Numero");
model.addColumn("Nom du Client");
model.addColumn("Adresse du Client");
model.addColumn("Telephone");
model.addColumn("Commande");
model.addColumn("Livraison");
model.addColumn("Retour");

			
try{
st=Connect.getConnection().createStatement();
rs=st.executeQuery("SELECT *FROM CLIENT");
while(rs.next())
{
model.addRow(new Object[]{rs.getString("idCli"), rs.getString("NomCli"), rs.getString("AdesCli"), rs.getString("TelepCli"),rs.getString("Command"), rs.getString("Livraisons"), rs.getString("Returne")});}
}
catch(Exception e){
System.err.println(e);}
table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldi = new javax.swing.JTextField();
        TextFieldCl1 = new javax.swing.JTextField();
        TextFieldCl2 = new javax.swing.JTextField();
        TextFieldCl3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ButtonAjCl = new javax.swing.JButton();
        ButtonAjCl1 = new javax.swing.JButton();
        ButtonAjCl2 = new javax.swing.JButton();
        ButtonActua = new javax.swing.JButton();
        buttonRC = new javax.swing.JButton();
        TextFieldRC = new javax.swing.JTextField();
        COCheckBox1 = new javax.swing.JCheckBox();
        RetCheckBox2 = new javax.swing.JCheckBox();
        LiCheckBox3 = new javax.swing.JCheckBox();
        ButtonActua1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Client ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom du Client");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adresse du Client");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Téléphone du Client");

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 51), null, new java.awt.Color(51, 0, 51)));
        table.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nom du Client", "Adresse du Client", "Téléphone", "Commande", "Livraisons", "Retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        ButtonAjCl.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ajouter.png"))); // NOI18N
        ButtonAjCl.setText("Ajouter");
        ButtonAjCl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjClActionPerformed(evt);
            }
        });

        ButtonAjCl1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/modifier.png"))); // NOI18N
        ButtonAjCl1.setText("Modifier");
        ButtonAjCl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjCl1ActionPerformed(evt);
            }
        });

        ButtonAjCl2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonAjCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer.png"))); // NOI18N
        ButtonAjCl2.setText("Supprimer");
        ButtonAjCl2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonAjCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjCl2ActionPerformed(evt);
            }
        });

        ButtonActua.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonActua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/actualiser.png"))); // NOI18N
        ButtonActua.setText("Actualiser");
        ButtonActua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonActua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActuaActionPerformed(evt);
            }
        });

        buttonRC.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        buttonRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/rechercher.png"))); // NOI18N
        buttonRC.setText("Recherche");
        buttonRC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 0), null, new java.awt.Color(102, 102, 0)));
        buttonRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRCActionPerformed(evt);
            }
        });

        COCheckBox1.setBackground(new java.awt.Color(0, 0, 102));
        COCheckBox1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        COCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        COCheckBox1.setText("Commande");
        COCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, new java.awt.Color(51, 51, 0)));
        COCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COCheckBox1ActionPerformed(evt);
            }
        });

        RetCheckBox2.setBackground(new java.awt.Color(0, 0, 102));
        RetCheckBox2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        RetCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        RetCheckBox2.setText("Retour");
        RetCheckBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, new java.awt.Color(51, 51, 0)));
        RetCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetCheckBox2ActionPerformed(evt);
            }
        });

        LiCheckBox3.setBackground(new java.awt.Color(0, 0, 102));
        LiCheckBox3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LiCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        LiCheckBox3.setText("Livraison");
        LiCheckBox3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, new java.awt.Color(51, 51, 0)));
        LiCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiCheckBox3ActionPerformed(evt);
            }
        });

        ButtonActua1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ButtonActua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/imprimer.png"))); // NOI18N
        ButtonActua1.setText("Imprimer");
        ButtonActua1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, new java.awt.Color(0, 0, 0)));
        ButtonActua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(345, 345, 345)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldCl3)
                            .addComponent(TextFieldCl2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(buttonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(364, 364, 364)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldRC)
                            .addComponent(TextFieldCl1)
                            .addComponent(TextFieldi))))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(ButtonAjCl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ButtonAjCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(COCheckBox1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ButtonAjCl2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonActua, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LiCheckBox3)
                                .addGap(147, 147, 147)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonActua1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RetCheckBox2))
                        .addGap(45, 45, 45)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldRC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldCl1)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4))
                    .addComponent(TextFieldCl3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldCl2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonAjCl)
                                .addComponent(ButtonAjCl1)
                                .addComponent(ButtonAjCl2)
                                .addComponent(ButtonActua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButtonActua1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LiCheckBox3)
                            .addComponent(COCheckBox1)
                            .addComponent(RetCheckBox2))
                        .addGap(124, 124, 124))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
try{
int i =table.getSelectedRow(); deplace(i);

}catch(Exception e){
JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void ButtonAjClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjClActionPerformed

String id=TextFieldi.getText(); 
String nom=TextFieldCl1.getText();
String ad=TextFieldCl3.getText();
String tel=TextFieldCl2.getText();
String Commande ="NO";
String Livre="NO";
String Retour ="NO";

if(COCheckBox1.isSelected())
{
Commande="YES";
}if(LiCheckBox3.isSelected())
{

Livre="YES";
}
if(RetCheckBox2.isSelected())
{
Retour="YES";

}

String query = "INSERT INTO `client`(`idCli`, `NomCli`, `AdesCli`, `TelepCli`,`Command`, `Livraisons`,Returne) VALUES ('"+id+"','"+nom+"','"+ad+"','"+tel+"','"+Commande+"','"+Livre+"','"+Retour+"')";

try{
      st.executeUpdate(query);
     JOptionPane.showMessageDialog(null,"Client ajouté avec succès");
     
     TextFieldi.setText("");
     TextFieldCl1.setText("");
     TextFieldCl3.setText("");
     TextFieldCl2.setText("");
     
     
     
}catch(SQLException | HeadlessException ex){
JOptionPane.showMessageDialog(null, ex.getMessage());
}
    }//GEN-LAST:event_ButtonAjClActionPerformed

    private void ButtonActuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActuaActionPerformed
try{
    model.setRowCount(0);
st=Connect.getConnection().createStatement();
rs=st.executeQuery("SELECT *FROM CLIENT");

while(rs.next())
{
model.addRow(new Object[]{rs.getString("idCli"), rs.getString("NomCli"), rs.getString("AdesCli"), rs.getString("TelepCli"),rs.getString("Command"), rs.getString("Livraisons"), rs.getString("Returne")});
}

}
catch(Exception e){

System.err.println(e);}  

table.setModel(model);
    }//GEN-LAST:event_ButtonActuaActionPerformed

    private void ButtonAjCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjCl1ActionPerformed
try{
if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
updatebtn();
                st.executeUpdate("UPDATE CLIENT SET NomCli='"+TextFieldCl1.getText()+"',AdesCli='"+TextFieldCl3.getText()+"',TelepCli='"+TextFieldCl2.getText()+"' WHERE idCli= "+TextFieldi.getText());
                
            } 

}catch(HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(null,"erreur de modifier !!!!!!!"+e.getMessage());
        System.err.println(e);} 
    }//GEN-LAST:event_ButtonAjCl1ActionPerformed

    private void ButtonAjCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjCl2ActionPerformed
try {

if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer un cient,est ce que tu est sure?"
                     ,"supprimer client",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
         
            if(TextFieldi.getText().length() != 0){
        st.executeUpdate("DELETE FROM CLIENT WHERE idCli= "+TextFieldi.getText());
             }//
            else { JOptionPane.showMessageDialog(null,"veuillez remplire le champ du numero !");}
}

catch(HeadlessException | SQLException e){

JOptionPane.showMessageDialog(null,"erreur de supprimer \n"+e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAjCl2ActionPerformed

    private void buttonRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRCActionPerformed
try{
model.setRowCount(0);

       {
       rs = st.executeQuery("SELECT * FROM CLIENT WHERE idCli = '"+TextFieldRC.getText()+"'");
       }
       
       while(rs.next())
       {
              Object [] client ={rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4)};
              model.addRow(client);
       }
       
       if(model.getRowCount() == 0 )
       {
           JOptionPane.showMessageDialog(null," Aucun client disponible");
       }else
       {
           int i=0;
           deplace(i);
       
       }

}

catch(SQLException | HeadlessException e){
System.err.println(e);
JOptionPane.showMessageDialog(null,e.getMessage());

}        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRCActionPerformed
public void updatebtn()
    {
        String nom=TextFieldCl1.getText();
        String ad=TextFieldCl3.getText();
        String tel=TextFieldCl2.getText();
        String id = TextFieldi.getText();
    String Commande="NO";
    String Retour="NO";
    String Livre="NO";
    
    
    
    if(COCheckBox1.isSelected()){

Commande="YES";
}if(LiCheckBox3.isSelected()){

Livre="YES";
}if(RetCheckBox2.isSelected()){Retour="YES";}

    String query = "UPDATE `client` SET `NomCli`='"+nom+"',`AdesCli`='"+ad+"',`TelepCli`='"+tel+"',`Command`='"+Commande+"',`Livraisons`='"+Livre+"',`Returne`='"+Retour+"' WHERE `idCli`='"+id+"'";

try{
  st=Connect.getConnection().createStatement();



JOptionPane.showConfirmDialog(null, "Voulez-vous appliquée la modification ?");
st.executeUpdate(query);
}catch(SQLException e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
    }
    private void COCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COCheckBox1ActionPerformed
        boolean etat=COCheckBox1.isSelected();

    }//GEN-LAST:event_COCheckBox1ActionPerformed

    private void RetCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetCheckBox2ActionPerformed

    private void LiCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LiCheckBox3ActionPerformed

    private void ButtonActua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActua1ActionPerformed
MessageFormat header = new MessageFormat("Bon de Commande");
MessageFormat footer = new MessageFormat("Page[0,number,integer]");

try{

        table.print(JTable.PrintMode.NORMAL, header, footer);

}catch(java.awt.print.PrinterException e){
System.err.format("Erreur d'impression", e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActua1ActionPerformed
private void deplace(int i)
{
try{
TextFieldi.setText(model.getValueAt(i, 0).toString());
TextFieldCl1.setText(model.getValueAt(i, 1).toString());
TextFieldCl3.setText(model.getValueAt(i, 2).toString());
TextFieldCl2.setText(model.getValueAt(i, 3).toString());
    
    
}catch(Exception e){
System.err.println(e);

JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
}
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormulaireClient().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActua;
    private javax.swing.JButton ButtonActua1;
    private javax.swing.JButton ButtonAjCl;
    private javax.swing.JButton ButtonAjCl1;
    private javax.swing.JButton ButtonAjCl2;
    private javax.swing.JCheckBox COCheckBox1;
    private javax.swing.JCheckBox LiCheckBox3;
    private javax.swing.JCheckBox RetCheckBox2;
    private javax.swing.JTextField TextFieldCl1;
    private javax.swing.JTextField TextFieldCl2;
    private javax.swing.JTextField TextFieldCl3;
    private javax.swing.JTextField TextFieldRC;
    private javax.swing.JTextField TextFieldi;
    private javax.swing.JButton buttonRC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
